"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&ti26f#x*18x0=dl8s)p5&m$2@bjh0hnx0ly$ri4*6kouubh(s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Sizning ilovangiz
    'shop_app',
    
    # django-allauth requirements
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Optionally enable Jazzmin admin theme if the package is available.
# This prevents Django from failing to import when Jazzmin isn't installed.
try:
    import importlib
    if importlib.util.find_spec('jazzmin') is not None:
        # Put jazzmin before 'django.contrib.admin' so it can customize admin templates
        INSTALLED_APPS.insert(0, 'jazzmin')
except Exception:
    # If anything goes wrong here, keep going without Jazzmin.
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Allauth middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
import os


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'shop_app.CustomUser'
WHITENOISE_MANIFEST_STRICT = False
# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Google OAuth sozlamalari
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Tizimga muvaffaqiyatli kirgandan keyingi yo'naltirish
LOGIN_REDIRECT_URL = '/'


# --- DYNAMIC SITE_ID ANIQLESH TIZIMI ---
# Bazadagi sayt ID raqami chalkashib ketmasligi uchun avtomatik topish
SITE_ID = 1
if 'runserver' in sys.argv:
    try:
        from django.contrib.sites.models import Site
        # Agar bazada 127.0.0.1:8000 bo'lsa uni ID sini oladi
        site = Site.objects.filter(domain="127.0.0.1:8000").first()
        if site:
            SITE_ID = site.id
        else:
            first_site = Site.objects.first()
            if first_site:
                SITE_ID = first_site.id
    except Exception:
        SITE_ID = 1


JAZZMIN_SETTINGS = {
    # Brauzer tabidagi sarlavha (Title)
    "site_title": "Mening Loyiham Admin",

    # Admin panelning chap tepa burchagidagi sarlavha
    "site_header": "Loyiham Boshqaruvi",

    # Tizimga kirish oynasidagi sarlavha (Login screen)
    "site_brand": "Loyiham Admin",

    # Sayt logosi (static papkangizda bo'lishi kerak, masalan: static/img/logo.png)
    # "site_logo": "img/logo.png",

    # Tizimga kirish oynasidagi logo
    # "login_logo": "img/logo.png",

    # Sayt logosi uchun CSS klass (aylana shaklda bo'lishi uchun)
    "site_logo_classes": "img-circle",

    # Xush kelibsiz matni
    "welcome_sign": "Xush kelibsiz! Boshqaruv paneliga kirish uchun login va parolingizni kiriting.",

    # Mualliflik huquqi matni (Footer)
    "copyright": "Mening Kompaniyam MChJ",

    # Qidiruv maydoni (barcha modellar ichidan qidirish uchun model nomi)
    "search_model": "auth.User",

    # Foydalanuvchi menyusi (o'ng tepada profildan ochiladigan qism)
    "user_avatar": None,  # Agar foydalanuvchi modelida rasm bo'lsa, maydon nomini yozing (masalan: 'profile_pic')

    ############
    # Top Menu #
    ############
    # Tepada chiquvchi havolalar (Links)
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Saytga o'tish", "url": "/", "new_window": True},
    ],

    #############
    # Side Menu #
    #############
    # Chap menyuni daraxtsimon (Tree) ko'rinishga keltirish
    "show_sidebar": True,
    "navigation_expanded": True,

    # Ilovalar (Apps) va modellarga ikonka (FontAwesome 5) biriktirish
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Ikonka topilmaganda standart holatda chiqadigan belgi
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Tashqi kalitlar (ForeignKey) bilan ishlashda yangi oyna ochmasdan modal ko'rinishida qo'shish
    "related_modal_active": True,

    #############
    # UI Custom #
    #############
    # Admin panel ichida foydalanuvchiga interfeys ranglarini o'zgartirishga ruxsat berish (sozlab bo'lingach false qilish tavsiya etiladi)
    "show_ui_builder": True,
}

# Ranglar va UI ko'rinishi (Mavzular)
JAZZMIN_UI_TWEAKS = {
    # To'q rangli (Dark mode) mavzu yoqish variantlari:
    # "theme": "flatly", # Yorug' variant uchun eng chiroylilaridan biri
    "theme": "darkly",  # To'q rangli (Dark mode) chiroyli mavzu
    "dark_mode_theme": "darkly",
    
    # Navbar va sidebar ranglari
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True, # Chap menyudagi ichma-ich elementlarni surib ko'rsatish
}
